### ISSUE TITLE
The black theme does not display colored icons

### ISSUE THREAD

**Issue by lunik1981** [DotOS/android_packages_apps_DotUICenter#1]
The black theme does not display colored icons
![1](https://user-images.githubusercontent.com/25451991/41199288-c2e4658c-6c97-11e8-9624-f406a1a4fae7.png)
![2](https://user-images.githubusercontent.com/25451991/41199289-c302e0a2-6c97-11e8-89b5-380af71377d2.png)
![3](https://user-images.githubusercontent.com/25451991/41199290-c328ae5e-6c97-11e8-9251-afefc74710f0.png)

**Comment by mohancm** [comment]
Colored icons doesn't look good on black theme
